#============================================================================
# init.vim --- My SpaceVim config
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
#=============================================================================

# SpaceVim options {{{
[options]
    default_indent = 2
    enable_debug = 1
    enable_ale = 1
    filemanager = 'nerdtree'
    filetree_direction = "right"
    enable_ycm = 0
    snippet_engine = "ultisnips"
    line_on_the_fly = 1
    default_custom_leader = ","
    enable_statusline_mode = true
    enable_ale = true
    enable_neomake = true
    realtime_leader_guide = 1
    enable_tabline_filetype_icon = true
    enable_os_fileformat_icon = true
    statusline_unicode_symbols = true
    buffer_index_type = 0
    windows_index_type = 3
    statusline_separator = 'arrow'
    github_username = 'casjay'
    auto_disable_touchpad = 0
    colorscheme = 'space-vim-dark'
    checkinstall = true
    guifont = 'Hack Nerd Font:h12:cANSI:qDRAFT'
    enable_tabline_filetype_icon = true
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    search_tools = ["fzf", "rg", "pt", "ack", "grep", "findstr"]
    autocomplete_method = "coc"
    commandline_prompt = '>'
    vimcompatible = true
    # enable_language_specific_leader = false
    enable_statusline_tag = true
# }}}

# SpaceVim layer config {{{
[[layers]]
    name = 'core'
    filetree_show_hidden = true

[[layers]]
    name = 'coc'

[[layers]]
    name = "lang#python"

[[layers]]
    name = 'format'

[[layers]]
    name = 'git'

[[layers]]
    name = 'tools'

[[layers]]
    name = 'gtags'
    gtagslabel = 'pygments'

[[layers]]
    name = 'cscope'

[[layers]]
    name = 'VersionControl'

[[layers]]
    name = 'lang#vim'

[[layers]]
    name = 'lang#c'

[[layers]]
    name = 'lang#scala'

[[layers]]
    name = 'lang#lua'

[[layers]]
    name = 'lang#sh'
    bash-file-head = [
        '#!/usr/bin/env bash',
        '# Time: `strftime("%Y-%m-%d %T")`',
        ''
    ]

[[layers]]
    name = 'lang#lisp'

[[layers]]
    name = 'lang#xml'

[[layers]]
    name = 'debug'

[[layers]]
    name = 'lang#toml'

[[layers]]
    name = 'colorscheme'

[[layers]]
    name = 'core#statusline'
    enable = true

[[layers]]
    name = 'core#tabline'
    enable = true

[[layers]]
    name = 'autocomplete'
    auto-completion-delay = 10
    auto-completion-return-key-behavior = "smart"
    auto-completion-tab-key-behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
  name = 'shellcheck'

[[custom_plugins]]
    name = 'jreybert/vimagit'
    merged = false

[[custom_plugins]]
    name = 'liuchengxu/space-vim-dark'
